### ISSUE TITLE
[Swift] Cannot build Swift project

### ISSUE THREAD

**Issue by gmosx** [IBM-Bluemix/ibm-cloud-developer-tools#10]
I create a simple Swift executable project:

```
swift package init --type=executable
```

I enable idt support:

```
bx dev enable
```

I try to build locally:

```
bx dev build
```

And I get the following error:

```
Building the project in the current directory started at Sun Sep  3 11:31:01 2017
FAILED                
Failed to build the project.

Dumping output from the command: 
Current folder: /swift-project
Command: build
Build configuration: release
Build folder: /swift-project/.build-ubuntu
Compiling the project...
Build configuration: release
/swift-utils/tools-utils.sh: line 52: swift: command not found

Stopping the '****-swift-tools' container...
OK
```

**Comment by kfbishop** [comment]
The "enable" action requires an actual runnable server-side project, such as used with Kitura,  Vapor, or similar.  A generic Swift executable does not have enough content to be buildable and runnable within the cloud.   

Using a Kitura sample project like this one works as expected - https://github.com/IBM-Swift/Kitura-Sample.git.  Note: I did have to manually rename the runnable in the Dockerfile to get this sample to work as expected.  We'll get this resolved shortly as well.

I'll open a new issue in our internal repo to attempt to identify these non-functional Server-Side projects and provide more direct guidance.

If you have more questions, please [reach out on slack](https://ibm.biz/IBMCloudNativeSlack) - `#developer-tools`.

**Comment by gmosx** [comment]
But, I would like to run a simple service that e.g. performs a simple calculation every 1h and sends an email or a slack message, why should I need to use Kitura for something like this?

**Comment by gmosx** [comment]
BTW I tried creating a Basic Web App wit IDE, i.e.

`bx dev create`

And I got the same error:

```
Compiling the project...
Build configuration: release
/swift-utils/tools-utils.sh: line 52: swift: command not found
```

This is a standard Kitura application generated by IDT.

**Comment by kfbishop** [comment]
Hi @gmosx,   I'm not sure what to say about the error above.   I'll have one of the Swift engineers look into this.  Can you try and re-run the build using the trace argument and posting here.
Ex. `bx dev build --trace`

**Comment by christiancompton** [comment]
@gmosx Can you also provide environment information - OS version/docker version/bx dev plugin version/etc?  I will attempt to replicate.

**Comment by tunniclm** [comment]
@gmosx Can you check the output of `docker images` for image `ibmcom/swift-ubuntu`?

Mine is:
```
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
ibmcom/swift-ubuntu           3.1.1               39995571098d        2 months ago        1.19 GB
```

Does your image id match this? If not, what is it?

**Comment by gmosx** [comment]
@kfbishop 

The relevant part of the `bx dev build --trace` output is:

```
Successfully tagged postsreader-swifttools:latest
OK
Creating a container named 'postsreader-swift-tools' from that image...
OK
Starting the 'postsreader-swift-tools' container...
OK
Building the project in the current directory started at Fri Sep  8 19:58:50 2017
Executing command 'cd /swift-project; /swift-utils/tools-utils.sh build release' on container postsreader-swift-tools using user gmoschovitis
Current folder: /swift-project
Command: build
Build configuration: release
Build folder: /swift-project/.build-ubuntu
Compiling the project...
Build configuration: release
/swift-utils/tools-utils.sh: line 52: swift: command not found
FAILED
Failed to build the project.

FAILED
Failed to build the project.
Stopping the 'postsreader-swift-tools' container...
OK
```

**Comment by gmosx** [comment]
@tunniclm Hmm... I seem to have multiple versions:

```
ibmcom/swift-ubuntu-runtime                    3.1.1               2069f5300440        4 months ago        277MB
ibmcom/swift-ubuntu                            3.1.1               b689c18b00db        4 months ago        1.17GB
ibmcom/swift-ubuntu-runtime                    3.0.2               9d519121012d        6 months ago        276MB
ibmcom/swift-ubuntu                            3.0.2               61d08bcc4dea        6 months ago        1.16GB
ibmcom/swift-ubuntu                            latest              61d08bcc4dea        6 months ago        1.16GB
```

**Comment by gmosx** [comment]
@christiancompton Lates macOS (Sierra), latest docker, latest bx-dev

**Comment by tunniclm** [comment]
@gmosx Your image ID is `b689c18b00db`, which is indeed different to latest. I think you may have a version of the `3.1.1` swift-ubuntu image used a different location for the `swift` executable than is expected by the latest version of the script `tools-utils.sh`. This is just a theory, but I think it bears investigating.

**Comment by gmosx** [comment]
Hmm... I deleted my images from the local registry and now everything seems to work correctly.
