### ISSUE TITLE
Please add IDT to IBM Cloud Application Tools 2 Mac Application

### ISSUE THREAD

**Issue by gmosx** [IBM-Bluemix/ibm-cloud-developer-tools#12]
`IBM Cloud Application Tools 2` (https://console.bluemix.net/docs/cli/icat.html#icat) is a useful Mac application. It would be great to integrate IDT with this Mac app.

**Comment by kfbishop** [comment]
ICAT2 is not being maintained, and its unlikely at this time that we'll have any new releases.  If this changes in the future, it would be tightly integrated with the rest of the IDT suite.
