### ISSUE TITLE
cli-config name is too generic

### ISSUE THREAD

**Issue by gmosx** [IBM-Bluemix/ibm-cloud-developer-tools#14]
Please consider renaming `cli-config` to something more specific, e.g. `idt-config`.

**Comment by kfbishop** [comment]
I agree with the sentiment, but at this time there are no plans to rename this file.  

I will opening an issue on our internal GHE repo for this for the team to consider as tech-debt, and solicit feedback from dev team.  Closing this issue on public GH.

Internal ref:  arf/planning-localtools#690
Rename 'cli-config.yml' to something less generic
