### ISSUE TITLE
Add cli option to generate Kubernetes or Cloudfoundry files only

### ISSUE THREAD

**Issue by gmosx** [IBM-Bluemix/ibm-cloud-developer-tools#15]
AFAICS, the cli currently generates Cloudfoundry configuration files only and you need to manually update `cli-config` to support Kubernetes/Container-Service.

It would be great to provide a cli option (e.g. --platform={cloudfoundry|container}) to generate files for CF or k8s only (not both).

**Comment by kfbishop** [comment]
I agree that unused files are generally a bad thing. The consensus is that at the time of app creation, a   user may not know or care what the eventual deployment target will be.  This is why we provide assets for both CF and Kube.  The thinking is user either wont care, or can manually remove unneeded files as they see fit.  Also, choosing up front makes this difficult to change targets at a later time.

I'll bring this up to the larger architecture team (many squads involved in a change like this) and solicit feedback.  We are moving towards a more devops centric approach, where the developer wont typically be the one performing the deployments, but rather through a deployment pipeline.
Closing for now as wont fix, but may revisit in the future.
