### ISSUE TITLE
GIT_URL is dead

### ISSUE THREAD

**Issue by ianpartridge** [IBM-Bluemix/ibm-cloud-developer-tools#22]
https://github.com/IBM-Bluemix/ibm-cloud-developer-tools/blob/master/linux-installer/idt-installer#L13 has `GIT_URL="https://github.com/ibm-cloud-tools/ibm-cloud-developer"`

This URL is dead.

**Comment by kfbishop** [comment]
Thanks @ianpartridge -- I updated url.
